name: Create Tag on Release
on:
  release:
    types: [edited]
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag -a ${{ github.ref }} -m "Automated tag creation"
          git push --follow-tags
