name: Create Tag on Push
on:
  push:
    branches:
      - main
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
           fetch-depth: 0
      - name: Set committer identity
        run: |
          git config --global user.email "500069069@stu.upes.ac.in"
          git config --global user.name "Mayank Rastogi"
      - name: Get latest tag
        id: get_latest_tag
        run: echo ::set-output name=latest_tag::$(git describe --abbrev=0)
      - name: Create Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          latest_tag=$(/bin/echo -n "${{ steps.get_latest_tag.outputs.latest_tag }}")
          tag_version=${latest_tag##*.}
          next_tag_version=$((tag_version+1))
          new_tag="v1.0.${next_tag_version}"
          git tag -a $new_tag -m "Version $new_tag"
          git push --follow-tags
