name: Create Tag on Push
on:
  push:
    branches:
      - main
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set committer identity
        run: |
          git config --global user.email "500069069@stu.upes.ac.in"
          git config --global user.name "Mayank Rastogi"
      - name: Get latest tag
        id: get_latest_tag
        run: echo ::set-output name=latest_tag::$(git describe --abbrev=0)
      - name: Create Tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          latest_tag=$(/bin/echo -n "${{ steps.get_latest_tag.outputs.latest_tag }}")
          if [[ -z $latest_tag ]]; then
            new_tag="v1.0.0"
          else
            tag_version=$(git diff --name-only $latest_tag | awk -F'/' '{print $1}' | sort -u | wc -l)
            next_tag_version=$((tag_version+1))
            new_tag="v1.0.${next_tag_version}"
          fi
          git tag -a $new_tag -m "Version $new_tag"
          git push --follow-tags
