name: Create Tag on Push
on:
  push:
    branches:
      - main
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set committer identity
        run: |
          git config --global user.email "500069069@stu.upes.ac.in"
          git config --global user.name "Mayank Rastogi"
      - name: Get latest tag
        id: get_latest_tag
        run: echo ::set-output name=latest_tag::$(git describe --abbrev=0 --tags)
      - name: Increment tag version
        id: increment_tag_version
        run: echo ::set-output name=tag_version::$(echo "${{ steps.get_latest_tag.outputs.latest_tag }}" | awk -F. '{ printf("%d.%d.%d", $1, $2, $3+1) }')
      - name: Create tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag -a ${{ steps.increment_tag_version.outputs.tag_version }} -m "Version ${{ steps.increment_tag_version.outputs.tag_version }}"
          git push --follow-tags "https://github.com/${{ github.repository }}.git" HEAD:main
